import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import luaparse from "luaparse";
import { describe, expect, it } from "vitest";
import { readTocVersion } from "../src/core/addon";

const dir = path.resolve(__dirname, "..", "resources", "addon", "Vigil");
const tocText = readFileSync(path.join(dir, "Vigil.toc"), "utf8");

function tocField(name: string): string | null {
  const m = tocText.match(new RegExp(`^##\\s*${name}:\\s*([^\\r\\n]+)`, "m"));
  return m ? m[1]!.trim() : null;
}

const tocFiles = tocText
  .split(/\r?\n/)
  .map((l) => l.trim())
  .filter((l) => l && !l.startsWith("#"));
const luaFiles = tocFiles.map((f) => ({ name: f, text: readFileSync(path.join(dir, ...f.split("\\")), "utf8") }));
/** Hand-written files; Data\ is generated by scripts/addon-data.ts and checked by test/addon-data.test.ts. */
const sourceFiles = luaFiles.filter((f) => !f.name.startsWith("Data\\"));
const luaText = sourceFiles.map((f) => f.text).join("\n");

type Node = { type: string; [key: string]: unknown };

function walk(node: unknown, visit: (n: Node) => void) {
  if (Array.isArray(node)) {
    node.forEach((n) => walk(n, visit));
  } else if (node && typeof node === "object" && typeof (node as Node).type === "string") {
    visit(node as Node);
    for (const value of Object.values(node)) walk(value, visit);
  }
}

const asts = luaFiles.map((f) => luaparse.parse(f.text, { luaVersion: "5.1", scope: true, locations: true }));

/** Names the files assign or declare as globals. */
function globalWrites(): string[] {
  const names = new Set<string>();
  walk(asts, (n) => {
    if (n.type === "AssignmentStatement") {
      for (const target of n.variables as Node[]) {
        if (target.type === "Identifier" && !target.isLocal) names.add(target.name as string);
      }
    }
    if (n.type === "FunctionDeclaration" && !n.isLocal) {
      const id = n.identifier as Node | null;
      if (id?.type === "Identifier") names.add(id.name as string);
    }
  });
  return [...names].sort();
}

describe("bundled Vigil addon files", () => {
  it("is valid Lua 5.1 and only writes the globals the client and TOC expect", () => {
    for (const ast of asts) expect(ast.type).toBe("Chunk");
    expect(globalWrites()).toEqual([
      "SLASH_VIGIL1",
      "VigilDB",
      "Vigil_OnAddonCompartmentClick",
      "Vigil_OnAddonCompartmentEnter",
      "Vigil_OnAddonCompartmentLeave",
    ]);
  });

  it("shares state through the addon's private table", () => {
    for (const f of luaFiles) expect(f.text, f.name).toMatch(/^local (?:ADDON_NAME|_), ns = \.\.\.$/m);
  });

  it("loads on Classic Era, the Classic beta (Forever) and TBC Anniversary", () => {
    const interfaces = (tocField("Interface") ?? "").split(",").map((s) => s.trim());
    for (const n of interfaces) expect(n).toMatch(/^\d{5,6}$/);
    expect(interfaces).toEqual(expect.arrayContaining(["11507", "16001", "20505", "20506"]));
  });

  it("declares its SavedVariables, metadata and files", () => {
    expect(tocField("Title")).toBe("Vigil");
    expect(tocField("SavedVariables")).toBe("VigilDB");
    expect(tocField("Version")).toMatch(/^\d+\.\d+\.\d+$/);
    expect(tocFiles[0]).toBe("Core.lua");
    expect(tocFiles.at(-1)).toBe("Vigil.lua");
    expect(tocFiles).toEqual(expect.arrayContaining(["Data\\Bosses.lua", "Meter.lua", "Fight.lua", "Intel.lua", "LivePanel.lua", "IntelPanel.lua"]));
    expect(tocFiles.indexOf("Meter.lua")).toBeLessThan(tocFiles.indexOf("Fight.lua"));
    for (const f of tocFiles) expect(existsSync(path.join(dir, ...f.split("\\"))), f).toBe(true);
  });

  it("points the addon compartment at functions the Lua defines", () => {
    for (const field of ["AddonCompartmentFunc", "AddonCompartmentFuncOnEnter", "AddonCompartmentFuncOnLeave"]) {
      const name = tocField(field);
      expect(name, field).toMatch(/^Vigil_\w+$/);
      expect(luaText).toMatch(new RegExp(`^function ${name}\\(`, "m"));
    }
  });

  it("uses one version in the TOC, the Lua and the README example", () => {
    const version = readTocVersion(path.join(dir, "Vigil.toc"));
    const main = luaFiles.find((f) => f.name === "Vigil.lua")!.text;
    expect(main.match(/^local ADDON_VERSION = "([^"]+)"/m)?.[1]).toBe(version);
    expect(luaText.match(/^local ADDON_VERSION = /gm)).toHaveLength(1);
    const readme = readFileSync(path.join(dir, "README.md"), "utf8");
    expect(readme.match(/"addonVersion":"([^"]+)"/)?.[1]).toBe(version);
  });

  it("calls LoggingCombat only through the rate-limit-aware query and set", () => {
    // The client allows 5 LoggingCombat calls per 10 seconds, queries included; polling it flips the UI.
    const uses: string[] = [];
    walk(asts, (n) => {
      if (n.type !== "CallExpression") return;
      const base = n.base as Node;
      const args = n.arguments as Node[];
      if (base.type === "Identifier" && base.name === "LoggingCombat") uses.push("direct");
      if (args.some((a) => a.type === "Identifier" && a.name === "LoggingCombat")) {
        uses.push(`${base.type === "Identifier" ? (base.name as string) : "?"}/${args.length}`);
      }
    });
    expect(uses.sort()).toEqual(["pcall/1", "pcall/2", "type/1"]);
    expect(luaText).toMatch(/pcall\(LoggingCombat\)\r?\n/);
    expect(luaText).toMatch(/pcall\(LoggingCombat, want\)\r?\n/);
  });

  it("registers for combat events once, and only after asking whether the client allows it", () => {
    // On the 12.x engine the attempt alone can raise ADDON_ACTION_FORBIDDEN, a blocked-action popup.
    const fight = luaFiles.find((f) => f.name === "Fight.lua")!.text;
    const registrations = [...luaText.matchAll(/ns\.on\("COMBAT_LOG_EVENT_UNFILTERED"/g)];
    expect(registrations).toHaveLength(1);
    const init = fight.slice(fight.indexOf("function F.init()"));
    expect(init.indexOf("if not combatLogOpen() then")).toBeGreaterThan(-1);
    expect(init.indexOf("if not combatLogOpen() then")).toBeLessThan(init.indexOf('ns.on("COMBAT_LOG_EVENT_UNFILTERED"'));
    expect(luaText).not.toMatch(/ns\.RESTRICTED/);
  });

  it("only uses OnUpdate for dragging the minimap button; panels refresh from a timer", () => {
    const onUpdate = [...luaText.matchAll(/SetScript\("OnUpdate", ([^)]+)\)/g)].map((m) => m[1]);
    expect(onUpdate.sort()).toEqual(["nil", "onDragUpdate"]);
  });

  it("guards the client APIs that differ between Classic Era, TBC Anniversary and retail", () => {
    // Called only behind a type() check (or through ns.clean / ns.spellTexture / ns.spellName).
    for (const api of ["C_Spell.GetSpellTexture", "C_Spell.GetSpellInfo", "C_UnitAuras.GetAuraDataByIndex", "C_Timer.NewTicker"]) {
      const calls = [...luaText.matchAll(new RegExp(`${api.replace(".", "\\.")}\\(`, "g"))].length;
      const guards = [...luaText.matchAll(new RegExp(`type\\(${api.replace(".", "\\.")}\\) == "function"`, "g"))].length;
      expect(guards, api).toBeGreaterThanOrEqual(calls > 0 ? 1 : 0);
    }
    expect(luaText).not.toMatch(/[^.\w]GetSpellInfo\(/);
    expect(luaText).not.toMatch(/[^.\w]UnitBuff\(/);
    expect(luaText).not.toMatch(/\bstrsplit\(/);
  });

  it("has no middots or emoji in the addon", () => {
    for (const text of [tocText, ...luaFiles.map((f) => f.text), readFileSync(path.join(dir, "README.md"), "utf8")]) {
      expect(text.includes(String.fromCharCode(0xb7))).toBe(false);
      expect(/\p{Extended_Pictographic}/u.test(text)).toBe(false);
    }
  });
});
