// Generates the in-game addon's boss intel, resources/addon/Vigil/Data/Bosses.lua, from src/data/bosses.ts and
// src/data/dungeons/: `pnpm addon:data`. The Lua file is a committed artifact; test/addon-data.test.ts regenerates
// it and fails when it drifts from the TypeScript sources.
//
// Kept compact: per boss the NPC IDs, encounter IDs, names, instance and summary; per ability the name, spell IDs,
// what it does, the counter, and the client icon name (a fallback for clients whose GetSpellTexture lacks the spell).
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { BOSSES, INSTANCES, type Boss, type BossAbility, type Instance } from "../src/data/bosses";
import spellIcons from "../src/data/spell-icons.json";

const ROOT = path.resolve(__dirname, "..");
export const ADDON_DATA_DIR = path.join(ROOT, "resources", "addon", "Vigil", "Data");

const icons = spellIcons as { icons: string[]; spells: Record<string, number> };

/** A Lua string literal. Only escapes what Lua needs; UTF-8 passes through (the client renders it). */
function str(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\r?\n/g, "\\n")}"`;
}

const list = (values: (string | number)[]) => `{ ${values.map((v) => (typeof v === "number" ? String(v) : str(v))).join(", ")} }`;

function iconFor(a: BossAbility): string | null {
  if (a.icon) return a.icon;
  for (const id of a.spellIds) {
    const i = icons.spells[String(id)];
    if (i !== undefined && icons.icons[i]) return icons.icons[i]!;
  }
  return null;
}

function instanceLine(i: Instance): string {
  return `  [${str(i.id)}] = { n = ${str(i.name)}, s = ${str(i.short)}, k = ${str(i.kind)}, m = ${i.mapId} },`;
}

function abilityLine(a: BossAbility): string {
  const fields = [`n = ${str(a.name)}`];
  if (a.spellIds.length) fields.push(`id = ${list(a.spellIds)}`);
  const icon = iconFor(a);
  if (icon) fields.push(`ic = ${str(icon)}`);
  if (a.source) fields.push(`src = ${str(a.source)}`);
  fields.push(`d = ${str(a.summary)}`, `t = ${str(a.counter)}`);
  return `      { ${fields.join(", ")} },`;
}

function bossBlock(b: Boss): string {
  const head = [`k = ${str(b.key)}`, `n = ${str(b.name)}`, `i = ${str(b.instance)}`];
  const encounters = [...(b.encounterId === null ? [] : [b.encounterId]), ...(b.altEncounterIds ?? [])];
  if (encounters.length) head.push(`e = ${list(encounters)}`);
  if (b.npcIds.length) head.push(`ids = ${list(b.npcIds)}`);
  if (b.addNpcIds?.length) head.push(`adds = ${list(b.addNpcIds)}`);
  const names = b.unitNames.filter((n) => n !== b.name);
  if (names.length) head.push(`u = ${list(names)}`);
  if (b.rare) head.push("rare = true");
  if (b.status !== "full") head.push(`st = ${str(b.status)}`);
  const lines = [`  { ${head.join(", ")},`, `    s = ${str(b.summary)},`];
  if (b.abilities.length) {
    lines.push("    a = {", ...b.abilities.map(abilityLine), "    },");
  }
  lines.push("  },");
  return lines.join("\n");
}

/** File name (relative to the addon's Data folder) to contents. */
export function renderAddonData(): Record<string, string> {
  const header = [
    "-- Generated by scripts/addon-data.ts (pnpm addon:data) from src/data/bosses.ts and src/data/dungeons/. Do not edit.",
    "-- Bosses: k key, n name, i instance, e encounter IDs, ids NPC IDs, adds add NPC IDs, u other unit names,",
    "-- st intel status when not full, s summary, a abilities. Abilities: n name, id spell IDs, ic icon, src the add",
    "-- that casts it, d what it does, t what to do.",
    "",
    "local _, ns = ...",
    "ns.data = ns.data or {}",
    "",
  ];
  const used = new Set(BOSSES.map((b) => b.instance));
  const body = [
    "ns.data.instances = {",
    ...INSTANCES.filter((i) => used.has(i.id)).map(instanceLine),
    "}",
    "",
    "ns.data.bosses = {",
    ...BOSSES.map(bossBlock),
    "}",
    "",
  ];
  return { "Bosses.lua": [...header, ...body].join("\n") };
}

export function writeAddonData(dir = ADDON_DATA_DIR): string[] {
  mkdirSync(dir, { recursive: true });
  const files = renderAddonData();
  for (const [name, text] of Object.entries(files)) writeFileSync(path.join(dir, name), text);
  return Object.keys(files).map((name) => path.join(dir, name));
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(__filename)) {
  for (const file of writeAddonData()) console.log(`wrote ${path.relative(ROOT, file)}`);
}
